### ISSUE TITLE
Report generation fails

### ISSUE THREAD

**Issue by ChristianSchwarz** [jaredsburrows/gradle-license-plugin#13] opened 2017-03-29 11:23 UTC
When I create an empty sample project in Android Studio and run the licenseReleaseReport I get the following error:

```
Error:Execution failed for task ':app:licenseDebugReport'.
> Could not resolve all dependencies for configuration ':app:poms'.
   > Could not find :unspecified:.
     Searched in the following locations:
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/m2repository//unspecified//unspecified-.pom
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/m2repository//unspecified//unspecified-.pom
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository//unspecified//unspecified-.pom
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository//unspecified//unspecified-.pom
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository//unspecified//unspecified-.pom
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/android/m2repository//unspecified//unspecified-.pom
         file:/E:/Android Studio/gradle/m2repository//unspecified//unspecified-.pom
         file:/E:/Android Studio/gradle/m2repository//unspecified//unspecified-.pom
         https://jcenter.bintray.com//unspecified//unspecified-.pom
         https://jcenter.bintray.com//unspecified//unspecified-.pom
     Required by:
         project :app
```

**Comment by jaredsburrows** [comment] 2017-03-30 22:11
@ChristianSchwarz Thanks for the fast report!

Did you add the plugin at the root directory? or the App module?

**Comment by jaredsburrows** [comment] 2017-04-04 16:50
@ChristianSchwarz Any update for more information?

**Comment by ChristianSchwarz** [comment] 2017-04-06 10:40
@jaredsburrows 
I added the plugin to the app module. Hope that helps.

**Comment by dannyroa** [comment] 2017-04-19 07:08
I'm getting the same issue as well. I added it on every module's build.gradle.

**Comment by jaredsburrows** [comment] 2017-04-20 14:58
@ChristianSchwarz I looks like you are applying the plugin above the ":app:poms" module?

@dannyroa Does your error look similar?

**Comment by dannyroa** [comment] 2017-04-20 19:03
@jaredsburrows: Yup. Exactly the same.

**Comment by MathiasSeguy-Android2EE** [comment] 2017-05-02 14:53
Hi,
The same here.
Exactly the same.
apply plugin defined in the gradle file of main module (got just one). Sure it's at the right place.
And the stack:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:licenseMycmsMockDebugReport'.
> Could not resolve all dependencies for configuration ':app:poms'.
   > Could not find :unspecified:.
     Searched in the following locations:
         file:/D:/android-sdk/extras/m2repository//unspecified//unspecified-.pom
         file:/D:/android-sdk/extras/m2repository//unspecified//unspecified-.pom
         file:/D:/android-sdk/extras/google/m2repository//unspecified//unspecified-.pom
         file:/D:/android-sdk/extras/google/m2repository//unspecified//unspecified-.pom
         file:/D:/android-sdk/extras/android/m2repository//unspecified//unspecified-.pom
         file:/D:/android-sdk/extras/android/m2repository//unspecified//unspecified-.pom
         https://jcenter.bintray.com//unspecified//unspecified-.pom
         https://jcenter.bintray.com//unspecified//unspecified-.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by jaredsburrows** [comment] 2017-05-02 15:20
@MathiasSeguy-Android2EE Could you post your dependencies here? Usually this only happens if someone has a library project. Do you have a local aar or jar file?

**Comment by MathiasSeguy-Android2EE** [comment] 2017-05-02 16:08
Nope...
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    // Espresso
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations junit'
    })
    androidTestCompile('com.android.support.test.espresso:espresso-contrib:2.2.2') {
        // Necessary to avoid version conflicts
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'recyclerview-v7'
        exclude group: 'com.android.support', module: 'design'
    }
    // Runner
    androidTestCompile('com.android.support.test:runner:0.5') {
        // Necessary if your app targets Marshmallow (since the test runner
        // hasn't moved to Marshmallow yet)
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    testCompile('com.android.support.test:runner:0.5') {
        // Necessary if your app targets Marshmallow (since the test runner
        // hasn't moved to Marshmallow yet)
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    // ButterKnife
    compile 'com.jakewharton:butterknife:8.4.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
    // LeakCanary
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5'
    // Retrofit and co
    compile 'com.squareup.moshi:moshi:1.3.1'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.squareup.retrofit2:converter-moshi:2.1.0'
    compile 'com.squareup.okio:okio:1.11.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.5.0'
    // EventBus
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.android.support:appcompat-v7:25.2.0'
    androidTestCompile 'junit:junit:4.12'
    testCompile 'junit:junit:4.12'
    // Mockito
    testCompile 'org.mockito:mockito-core:2.7.19'
    // Design => for example snackbar
    compile 'com.android.support:design:25.2.0'
    compile 'com.android.support:cardview-v7:25.2.0'
    // NetWorkConnectionClass (Quality)
    compile 'com.facebook.network.connectionclass:connectionclass:1.0.1'
    //Google map
    compile 'com.google.android.gms:play-services-maps:10.2.0'
    compile 'io.balto:balto-sdk:2.1.0'

    //Dart and Henson
    compile 'com.f2prateek.dart:dart:2.0.2'
    compile 'com.f2prateek.dart:henson:2.0.2'
    provided 'com.f2prateek.dart:dart-processor:2.0.2'
    provided 'com.f2prateek.dart:henson-processor:2.0.2'
}

Sorry.

**Comment by jaredsburrows** [comment] 2017-05-02 16:33
@MathiasSeguy-Android2EE Thanks for helping me debug this! Usually when it says `unspecified`, it is looking for one of the following `G:A:V`(Group:ArtifactId/Name:Version).

Do you have any libraries in your "libs" folder? I see you have the following: `compile fileTree(include: ['*.jar'], dir: 'libs'`.

**Comment by kailash09dabhi** [comment] 2017-05-07 07:14
Same issue happening on my machine too! there is no lib folder too still!

**Comment by jaredsburrows** [comment] 2017-05-07 07:33
Working on test and updating the code now.

**Comment by jaredsburrows** [comment] 2017-05-08 05:52
This commit: https://github.com/jaredsburrows/gradle-license-plugin/commit/f2725455452c350561eb45b42954748a09cf9fb6 should have solved this issue. I making a `0.6.0` release now.

**Comment by jaredsburrows** [comment] 2017-05-08 19:09
This is duplicate of https://github.com/jaredsburrows/gradle-license-plugin/issues/4.

@ChristianSchwarz @dannyroa @MathiasSeguy-Android2EE @kailash09dabhi Please try the new version and let me know!

**Closed by jaredsburrows** 2017-05-08 19:09 UTC

**Comment by kailash09dabhi** [comment] 2017-05-18 13:20
Yes @jaredsburrows  good work! it works now!
