### ISSUE TITLE
Create variant specific output folders

### ISSUE THREAD

**Issue by sergeys-opera** [jaredsburrows/gradle-license-plugin#339] opened 2023-08-03 14:33 UTC
`LicenseReportTask` needs to run per variant (as variant dependencies might differ), thus, there might be multiple `LicenseReportTask` tasks defined in the project, e.g. `licenseDebugReport` or `licenseReleaseReport`. But all such tasks mark the same folder as their output making it impossible to add new tasks that depend on them. Gradle would think, for example, that a custom task `processLicenseDebugReport` is dependent on both `licenseDebugReport` and `licenseReleaseReport` as it uses files from the output folder of those tasks, while in reality it only depends on `licenseDebugReport`:
```
Reason: Task 'processLicenseDebugReport' uses this output of task
  'licenseReleaseReport' without declaring an explicit or implicit dependency
  This can lead to incorrect results being produced, depending on what order the
  tasks are executed.
```

There are two ways to fix this I think:
1. Declare each output file of `LicenseReportTask` as `@Output` 
2. Create different output folders per build variant, e.g. `licencesDebug` and `licensesRelease`

**Comment by realdadfish** [comment] 2023-08-18 13:11
Kind of a duplicate of #226

**Comment by jaredsburrows** [comment] 2024-01-29 20:43
Closed on duplicate.

**Closed by jaredsburrows** 2024-01-29 20:43 UTC
Labels: duplicate
